services:
    lof.mptrt.listener:
        class: lof\mptrt\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @template
            - @auth
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
